src/OnlineDocumentStore.MVC/Models/ErrorViewModel.cs
namespace OnlineDocumentStore.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/OnlineDocumentStore.MVC/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineDocumentStore.Application.DataTransferObjects.Auth;
using OnlineDocumentStore.Domain.Entities;
using OnlineDocumentStore.Domain.Exceptions;

namespace OnlineDocumentStore.MVC.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AuthController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
            => View();

        public async Task<IActionResult> Login()
            => View();

        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO loginDTO)
        {
            var user = await _userManager.FindByEmailAsync(loginDTO.Email);
            if (user == null)
                throw new Exception("User not found");

            var result = await _signInManager.PasswordSignInAsync(user, loginDTO.Password, false, false);

            if (!result.Succeeded)
                throw new Exception("There is an issue with signing in process");

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Register()
            => View();

        [HttpPost]
        public async Task<IActionResult> Register(RegisterDTO registerDTO)
        {
            var user = await _userManager.FindByEmailAsync(registerDTO.Email);

            if (registerDTO.Password != registerDTO.ConfirmPassword)
                throw new ValidationException("Passwords do not match!");

            if (user is not null)
                throw new ValidationException("You are already registred");

            user = new User()
            {
                UserName = registerDTO.Email,
                FullName = registerDTO.FullName,
                Email = registerDTO.Email,
                PhoneNumber = registerDTO.PhoneNumber,
                Salt = Guid.NewGuid().ToString(),
                ExpireDate = DateTime.Now.AddDays(2),
                RefreshToken = Guid.NewGuid().ToString(),
            };

            var identityResult = await _userManager.CreateAsync(user, registerDTO.Password);

            if (!identityResult.Succeeded)
                throw new Exception("There is an issue with signing in process");

            var result =
                await _signInManager.PasswordSignInAsync(user, registerDTO.Password, false, false);

            if (!result.Succeeded)
                throw new Exception("There is an issue with signing in process");

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Login");
        }
    }
}

src/OnlineDocumentStore.MVC/Controllers/DocumentsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineDocumentStore.Application.Services.DocumentServices;
using OnlineDocumentStore.Application.Services.PDFFileServices;

namespace OnlineDocumentStore.MVC.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly IDocumentService _documentService;
        private readonly IPDFFileService _pdfFileService;

        public DocumentsController(
            IDocumentService documentService,
            IPDFFileService pdfFileService)
        {
            _documentService = documentService;
            _pdfFileService = pdfFileService;
        }

        [Route("/Documents/{id}")]
        public async Task<IActionResult> GetDocumentAsync(Guid id)
        {
            var document = await _documentService.GetByIdAsync(id);
            return View(document);
        }

        public async Task<IActionResult> DownloadFileAsync(string path)
        {
            if (!System.IO.File.Exists(path))
                throw new Exception("File not found");

            var fileInfo = new System.IO.FileInfo(path);
            Response.ContentType = "application/pdf";
            Response.Headers.Add("Content-Disposition", "attachment;filename=\"" + fileInfo.Name + "\"");
            Response.Headers.Add("Content-Length", fileInfo.Length.ToString());

            // Send the file to the client
            return File(System.IO.File.ReadAllBytes(path), "application/pdf", fileInfo.Name);
        }
    }
}

src/OnlineDocumentStore.MVC/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineDocumentStore.MVC.Controllers
{
    public class FileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> DownloadFileAsync(string path)
        {
            if (!System.IO.File.Exists(path))
                throw new Exception("File not found");

            var fileInfo = new System.IO.FileInfo(path);
            Response.ContentType = "application/pdf";
            Response.Headers.Add("Content-Disposition", "attachment;filename=\"" + fileInfo.Name + "\"");
            Response.Headers.Add("Content-Length", fileInfo.Length.ToString());

            // Send the file to the client
            return File(System.IO.File.ReadAllBytes(path), "application/pdf", fileInfo.Name);
        }
    }
}

src/OnlineDocumentStore.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineDocumentStore.Application.DataTransferObjects;
using OnlineDocumentStore.Application.Services.DocumentServices;
using OnlineDocumentStore.Application.Services.PDFFileServices;
using OnlineDocumentStore.MVC.Models;
using System.Diagnostics;

namespace OnlineDocumentStore.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDocumentService _documentService;
        private readonly IPDFFileService _pdfFileService;

        public HomeController(IDocumentService documentService, IPDFFileService pdfFileService)
        {
            _documentService = documentService;
            _pdfFileService = pdfFileService;
        }

        [Authorize]
        public async Task<IActionResult> UploadDocumentAsync(PDFFile pdfFile)
        {
            var path = await _pdfFileService.AddPhotoAsync(pdfFile);

            if (!System.IO.File.Exists(path))
                throw new Exception("File not found");

            var fileInfo = new System.IO.FileInfo(path);
            Response.ContentType = "application/pdf";
            Response.Headers.Add("Content-Disposition", "attachment;filename=\"" + fileInfo.Name + "\"");
            Response.Headers.Add("Content-Length", fileInfo.Length.ToString());

            // Send the file to the client
            return File(System.IO.File.ReadAllBytes(path), "application/pdf", fileInfo.Name);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/OnlineDocumentStore.MVC/Views/Documents/GetDocument.cshtml
@using OnlineDocumentStore.Application.ViewModels
@model DocumentViewModel

<div class="container">
    <h1>@Model.Name</h1>

    <p>Yuklangan sana:@Model.UploadedDate</p>
           @*  public string UploadedFilePath { get; set; }
            public string EditedFilePath { get; set; } *@

    <h1>Author: @Model.User.FullName</h1>

    <a asp-controller="File" asp-action="DownloadFile" asp-route-path="@Model.EditedFilePath" class="btn btn-primary">Download this</a>
    <a asp-controller="File" asp-action="DownloadFile" asp-route-path="@Model.UploadedFilePath" class="btn btn-primary">Download Original</a>
</div>

src/OnlineDocumentStore.MVC/Views/Home/Index.cshtml
@using OnlineDocumentStore.Application.DataTransferObjects
@model PDFFile


@if (!User.Identity.IsAuthenticated)
{
    <div class="text-center">
        <h3>Amal bajarish uchun ro'yhatdan o'tgan va login qilgan bolishingiz kerak</h3>
        <a class="btn btn-primary" asp-controller="Auth" asp-action="Register">Ro'yhatdan o'tish</a>
        <a class="btn btn-primary" asp-controller="Auth" asp-action="Login">Kirish</a>
    </div>
}
else
{
    <form enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="File" class="form-label">Pdf file</label>
            <input asp-for="File" class="form-control" type="file" id="formFileMultiple" accept=".pdf" multiple>
        </div>

        <button class="btn btn-primary mt-1" asp-controller="Home" asp-action="UploadDocument" formmethod="post">Save</button>
    </form>
}

src/OnlineDocumentStore.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineDocumentStore.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineDocumentStore.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineDocumentStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="btn text-dark" asp-area="" asp-controller="Auth" asp-action="Profile">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-danger text-dark" asp-area="" asp-controller="Auth" asp-action="LogOut">Log out</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {   
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - OnlineDocumentStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>